apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptostalker-huobi
  labels:
    app: cryptostalker
    tier: huobi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptostalker
      tier: huobi
  template:
    metadata:
      labels:
        app: cryptostalker
        tier: huobi
    spec:
      containers:
      - name: huobi
        image: cryptostalker-huobi
        env:
        - name: GRPC_SERVER_ADDR
          value: "cryptostalker-aggregator:50051"
